Scanning images: 100%|██████████████████████| 477/477 [00:00<00:00, 3535.39it/s]
Scanning labels /media/tlab/Data/Dataset/Carm/wire/txt.cache3 (477 found, 0 missing, 0 empty, 0 duplicate, for 477 images): 477it [00:00, 19179.06it/s]











Scanning images: 100%|████████████████████████| 318/318 [00:24<00:00, 12.79it/s]
Scanning labels /media/tlab/Data/Dataset/Carm/wire/txt.cache3 (318 found, 0 missing, 0 empty, 0 duplicate, for 318 images): 318it [00:00, 16699.91it/s]
Images sizes do not match. This will causes images to be display incorrectly in the UI.
Image sizes 256 train, 256 test
Using 8 dataloader workers
Logging results to runs/train/yolov45
Starting training for 300 epochs...
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
     0/299     11.4G    0.1145    0.0756   0.01765    0.2078       272       256
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 287, in train
    pred = model(imgs)  # forward
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tlab/Tlab/pytorch/ObjectDetection/YOLOV4/models/models.py", line 464, in forward
    return self.forward_once(x)
  File "/home/tlab/Tlab/pytorch/ObjectDetection/YOLOV4/models/models.py", line 523, in forward_once
    x = module(x)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/tlab/anaconda3/envs/yo/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 102.00 MiB (GPU 0; 23.70 GiB total capacity; 21.93 GiB already allocated; 115.31 MiB free; 22.05 GiB reserved in total by PyTorch)